export {default as Navbar} from './NavBar/Navbar'
export {default as Home} from './HomePage/Home'
export {default as AddProducts} from './AddProducts/AddProducts'
export {default as Products } from './Products/Products'
export {default as Register} from './Register/Register'
export {default as Login} from './LoginPage/Login'